AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Template: Setup Transit Gateway and share it using AWS RAM.'

Parameters:
  SharedServiceAccountVPCID:
    Type: String
    Description: VPC ID for the shared-service account VPC.
    Default: vpc-0cf966816f0c0ac2a

  SharedServiceAccountRouteTableID:
    Type: String
    Description: The ID of the route table in the Aetonix VPC
    Default: rtb-0c7963c481fa9f819

  SharedServiceAccountSubnetIDs:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Comma-delimited list of subnet IDs in the Aetonix VPC for the Transit Gateway attachment.
    Default: "subnet-0bf75c815d474fbd3,subnet-07f94efd562b84549,subnet-044fd3e98a3ab6848"

  CrossAccountSharedAccountId:
    Type: String
    Description: AWS Account ID with which you want to share the Transit Gateway.
    Default: 762372983622 

  DevelopmentVPCCIDR:
    Type: String
    Description: CIDR block for the Development VPC.
    Default: "10.0.0.0/16"


Resources:
  MyTransitGateway:
    Type: 'AWS::EC2::TransitGateway'
    Properties:
      Description: 'Cross-account Transit Gateway'
      AutoAcceptSharedAttachments: 'enable'
      DefaultRouteTableAssociation: 'enable'
      DefaultRouteTablePropagation: 'enable'
      DnsSupport: 'enable'
      VpnEcmpSupport: 'enable'

  TransitGatewayAttachmentSharedService:
    Type: 'AWS::EC2::TransitGatewayVpcAttachment'
    Properties:
      TransitGatewayId: !Ref MyTransitGateway
      VpcId: !Ref SharedServiceAccountVPCID
      SubnetIds: !Ref SharedServiceAccountSubnetIDs

  TransitGatewayResourceShare:
    Type: 'AWS::RAM::ResourceShare'
    Properties:
      Name: 'Transit-Gateway-Resource-Share'
      Principals: 
        - !Ref CrossAccountSharedAccountId
      ResourceArns: 
        - !GetAtt MyTransitGateway.TransitGatewayArn
      AllowExternalPrincipals: false

  
  RouteToDevelopmentVPC:
    Type: 'AWS::EC2::Route'
    DependsOn: TransitGatewayAttachmentSharedService
    Properties:
      RouteTableId: !Ref SharedServiceAccountRouteTableID  
      DestinationCidrBlock: !Ref DevelopmentVPCCIDR
      TransitGatewayId: !Ref MyTransitGateway

Outputs:
  TransitGatewayID:
    Description: 'The ID of the Transit Gateway'
    Value: !Ref MyTransitGateway
  TransitGatewayAttachmentAetonixID:
    Description: 'The ID of the Transit Gateway Attachment for the Aetonix VPC'
    Value: !Ref TransitGatewayAttachmentSharedService
  TransitGatewayResourceShareID:
    Description: 'The ID of the Transit Gateway Resource Share'
    Value: !Ref TransitGatewayResourceShare
