AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Template: Attach shared Transit Gateway and update routes in the Development Account.'

Parameters:
  SharedTransitGatewayId:
    Type: String
    Description: The ID of the shared Transit Gateway.
    Default: tgw-0592a2fbf4aba5d78
    

  DevelopmentVPCID:
    Type: String
    Description: VPC ID for the Development VPC.
    Default: vpc-0f202cb342e012632

  DevelopmentSubnetIDs:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Comma-delimited list of subnet IDs in the Development VPC for the Transit Gateway attachment.
    Default: subnet-0d40d1b0f86eed6e1,subnet-0708e29057bcff7c9,subnet-01443d42878c89a5c

  SharedServiceAccountVPCCIDR:
    Type: String
    Description: CIDR block for the Aetonix VPC.
    Default: 10.20.0.0/16

  DevelopmentRouteTableID:
    Type: String
    Description: The ID of the route table in the Development VPC.
    Default: rtb-04b6f26e6b924da27

Resources:
  TransitGatewayAttachmentDevelopment:
    Type: 'AWS::EC2::TransitGatewayVpcAttachment'
    Properties:
      TransitGatewayId: !Ref SharedTransitGatewayId
      VpcId: !Ref DevelopmentVPCID
      SubnetIds: !Ref DevelopmentSubnetIDs

  RouteToSharedServiceAccountVPC:
    Type: 'AWS::EC2::Route'
    DependsOn: TransitGatewayAttachmentDevelopment
    Properties:
      RouteTableId: !Ref DevelopmentRouteTableID
      DestinationCidrBlock: !Ref SharedServiceAccountVPCCIDR
      TransitGatewayId: !Ref SharedTransitGatewayId

Outputs:
  TransitGatewayAttachmentDevelopmentID:
    Description: 'The ID of the Transit Gateway Attachment for the Development VPC'
    Value: !Ref TransitGatewayAttachmentDevelopment
